apiVersion: governance.nazar.grynko.com/v1alpha1
kind: ManifestRequestTemplate
metadata:
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/managed-by: kustomize
  name: manifestrequesttemplate-sample
spec:
  # TODO(user): Add fields here
