# This patch adds host.minikube.internal to the webhook certificate for local Minikube development
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qubmango-controller-serving-cert
  namespace: controller-system
spec:
  dnsNames:
  - host.minikube.internal
  - localhost