apiVersion: v1
kind: Secret
metadata:
  name: local-controller-manager-token
  namespace: controller-system
  # Tell Kubernetes to populate the secret with a token
  annotations:
    kubernetes.io/service-account.name: "local-controller-controller-manager"
type: kubernetes.io/service-account-token