apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
  annotations:
    # Setting the annotation to null removes it
    cert-manager.io/inject-ca-from: null
webhooks:
- name: mca-webhook.governance.nazar.grynko.com
  clientConfig:
    # remove service (to use url instead for forwarding traffic to local instance) 
    service: null
    # specify proxy url
    url: https://inappreciatively-adopted-saige.ngrok-free.dev/validate-all
    # disable caBundle to skip proxy verification
    caBundle: ""