apiVersion: v1
data:
  token: YXRyMi0xMTI1NDUwMTEyNjUyMTM1ODMtNTY4Mjk3ODYzMjk5NTY3OTYtajFmc2RmQVM1YWRmbW54SFZ5ckZhc2RsMFhQMQ==
kind: Secret
metadata:
  name: slack-secret-my
  namespace: test-ns
type: Opaque
