apiVersion: v1
data:
  passphrase: c3NoLXBhc3NwaHJhc2U=
  ssh-privateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQ21GbGN6STFOaTFqWW1NQUFBQUdZbU55ZVhCMEFBQUFHQUFBQUJEY0xGaGhLbwpVVUhxOGNhM3UwNGVQSEFBQUFFQUFBQUFFQUFBQXpBQUFBQzNOemFDMWxaREkxTlRFNUFBQUFJTXdka2pZcnVHeERrWERvCjJuUXRLMG5NLzcrNU9vczAwV3dYOSs2NEFHV0JBQUFBa0N1eHVyc1FOamg1dTNEZFFqVjJpNzladVQ0b2J3TUtiMjh1ZlkKYjhaZ1lqUjhuTVZZUHBtQzhZK2hLVUR0emNsVFlOWXpjZ1RsSjBpd2VSbHg2ei9ubUd0UmE0Z2lWZVV4MDN2ZUJqU3dvaQpzYWhYSGtGK1JBT01UK3MydzVTTU5nNVlvSEE4MjR5QzR5YTIyQ0EvY0ZKQVg4OW9tUGVRZEJmT2l5YjFTRlFUMXk4ZEVICjVqVmFjM1V4YmRXMnlUaUE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K
kind: Secret
metadata:
  name: ssh-secret-my
  namespace: test-ns
type: Opaque
