apiVersion: v1
data:
  passphrase: c3NoLXBhc3NwaHJhc2U=
  ssh-privateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQ21GbGN6STFOaTFqWW1NQUFBQUdZbU55ZVhCMEFBQUFHQUFBQUJBMy9vSURCUAp4cENUS2s0dmxrTCtGSEFBQUFFQUFBQUFFQUFBQXpBQUFBQzNOemFDMWxaREkxTlRFNUFBQUFJSjJlWFM4OVJaTmc5MnNGCm8reHEvNVJIUmFRV1F4WGQ2bUhFWkhIR3lCNGJBQUFBa0Y4THpyQUtZd3BTRzUrOXh4cTVMZVR6WUdOZ21TOXF6SFBIVlMKbzkrbGMzVkJKYjc3U3FCN0o2d1FHdDRoa0wzZFBLQ0x5eWlkOEVmS2V6SzFkZjNsV0Zzc1JlNXg2dHhmMDlDcmdSWC9RYQpUWmtaMVpoa2JBOXI5TmZtTGN5eURKNFBoQWVyUW5OU3pPWi85dFBHOWpFSEFaeDZwYUdwM25KVTJaektxRWhhY3U4UzE2CkFEMW5Eemw2OWVRTUMyNUE9PQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0=
kind: Secret
metadata:
  name: ssh-secret-my
  namespace: test-ns
type: Opaque
