apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
# Create a config file with known_hosts in it
- name: governance-operator-known-hosts
  files:
  - assets/known_hosts