---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: manifestrequesttemplates.governance.nazar.grynko.com
spec:
  group: governance.nazar.grynko.com
  names:
    kind: ManifestRequestTemplate
    listKind: ManifestRequestTemplateList
    plural: manifestrequesttemplates
    singular: manifestrequesttemplate
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ManifestRequestTemplate is the Schema for the manifestrequesttemplates
          API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of ManifestRequestTemplate
            properties:
              argoCD:
                description: ArgoCD contains information about the git repository,
                  branch and path where manifests are stored.
                properties:
                  application:
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                    required:
                    - name
                    - namespace
                    type: object
                required:
                - application
                type: object
              gitRepository:
                properties:
                  ssh:
                    properties:
                      secretsRef:
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                        required:
                        - name
                        - namespace
                        type: object
                      url:
                        type: string
                    required:
                    - secretsRef
                    - url
                    type: object
                required:
                - ssh
                type: object
              governanceFolderPath:
                type: string
              governors:
                description: Required until GovernorsRef is implemented.
                properties:
                  members:
                    description: List of governors.
                    items:
                      properties:
                        alias:
                          description: Alias for governor (for easier identification)
                          minLength: 1
                          type: string
                        publicKey:
                          description: PublicKey of the governor used to verify signatures.
                          minLength: 1
                          type: string
                      required:
                      - alias
                      - publicKey
                      type: object
                    type: array
                  notificationChannels:
                    description: General list of notification channels to inform governors
                      about pending approvals.
                    items:
                      properties:
                        slack:
                          properties:
                            channelID:
                              description: Slack channel ID to notify (e.g., S01234567)
                              minLength: 1
                              type: string
                          required:
                          - channelID
                          type: object
                      type: object
                    type: array
                required:
                - members
                type: object
              mca:
                description: MCA contains information about MCA metadata.
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                - namespace
                type: object
              msr:
                description: MSR contains information about MSR metadata.
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                required:
                - name
                - namespace
                type: object
              notifications:
                description: NotificationConfig holds the configuration for different
                  notification providers.
                properties:
                  slack:
                    description: |-
                      Slack contains the configuration for Slack notifications, including the token secret.
                      If this field is omitted, Slack notifications will be disabled.
                    properties:
                      secretsRef:
                        description: SecretsRef points to the Secret containing the
                          'token' key for the Slack Bot.
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                        required:
                        - name
                        - namespace
                        type: object
                    required:
                    - secretsRef
                    type: object
                type: object
              pgp:
                properties:
                  publicKey:
                    minLength: 1
                    type: string
                  secretsRef:
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                    required:
                    - name
                    - namespace
                    type: object
                required:
                - publicKey
                - secretsRef
                type: object
              require:
                description: |-
                  The policy rules for approvals.
                  Required until ApprovalRuleRef is implemented.
                properties:
                  all:
                    description: If true, all child rules must be satisfied.
                    type: boolean
                  atLeast:
                    description: Specifies the minimum number of child rules that
                      must be satisfied.
                    minimum: 1
                    type: integer
                  require:
                    description: List of child rules.
                    x-kubernetes-preserve-unknown-fields: true
                  signer:
                    description: Signer can be either PublicKey or Alias of the governor.
                      If alias is used, it should start with `$` to distinguish it
                      from PublicKey.
                    minLength: 1
                    type: string
                type: object
              version:
                description: |-
                  Version is the current version of the ManifestRequestTemplate.
                  Each new MRT must have a version higher than the previous one.
                minimum: 1
                type: integer
            required:
            - argoCD
            - gitRepository
            - governors
            - mca
            - msr
            - pgp
            - require
            - version
            type: object
          status:
            description: status defines the observed state of ManifestRequestTemplate
            properties:
              actionState:
                description: ActionState tracks the progress of the main reconcile.
                type: string
              applicationInitTargetRevision:
                type: string
              conditions:
                description: |-
                  conditions represent the current state of the ManifestRequestTemplate resource.
                  Each condition has a unique type and reflects the status of a specific aspect of the resource.
                  The status of each condition is one of True, False, or Unknown.
                items:
                  description: Condition contains details for one aspect of the current
                    state of this API Resource.
                  properties:
                    lastTransitionTime:
                      description: |-
                        lastTransitionTime is the last time the condition transitioned from one status to another.
                        This should be when the underlying condition changed.  If that is not known, then using the time when the API field changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: |-
                        message is a human readable message indicating details about the transition.
                        This may be an empty string.
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      description: |-
                        observedGeneration represents the .metadata.generation that the condition was set based upon.
                        For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
                        with respect to the current state of the instance.
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      description: |-
                        reason contains a programmatic identifier indicating the reason for the condition's last transition.
                        Producers of specific condition types may define expected values and meanings for this field,
                        and whether the values are considered a guaranteed API.
                        The value should be a CamelCase string.
                        This field may not be empty.
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      description: status of the condition, one of True, False, Unknown.
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: type of condition in CamelCase or in foo.example.com/CamelCase.
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
                x-kubernetes-list-map-keys:
                - type
                x-kubernetes-list-type: map
              deletionProcessingState:
                description: DeletionProcessingState tracks the progress of the deletion
                  process.
                type: string
              lastObservedCommitHash:
                description: LastObservedCommitHash is the last observed commit hash
                  from the git repository
                type: string
              revisionProcessingStep:
                description: RevisionProcessingState tracks the progress of the revision
                  processing.
                type: string
              revisionQueueRef:
                description: RevisionsQueueRef is the reference to the dedicated queue
                  CRD.
                properties:
                  name:
                    type: string
                  namespace:
                    type: string
                type: object
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
