apiVersion: governance.nazar.grynko.com/v1alpha1
kind: GovernanceEvent
metadata:
  labels:
    app.kubernetes.io/name: kubernetes
    app.kubernetes.io/managed-by: kustomize
  name: governanceevent-sample
spec:
  # TODO(user): Add fields here
