## Append samples of your project ##
resources:
- governance_v1alpha1_manifestrequesttemplate.yaml
- governance_v1alpha1_manifestchangeapproval.yaml
- governance_v1alpha1_manifestsigningrequest.yaml
- governance_v1alpha1_governancequeue.yaml
- governance_v1alpha1_governanceevent.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
